import { Achievement } from '../types';

export const createComprehensiveAchievements = (): Achievement[] => {
  return [
    {
      id: crypto.randomUUID(),
      title: 'First Step',
      description: 'Add your first professional contact',
      earned: false,
      icon: '🎯',
      category: 'milestone',
      requirement: 1,
      progress: 0,
      points: 10,
    },
    {
      id: crypto.randomUUID(),
      title: 'Network Builder',
      description: 'Add 5 professional contacts',
      earned: false,
      icon: '👥',
      category: 'milestone',
      requirement: 5,
      progress: 0,
      points: 25,
    },
    {
      id: crypto.randomUUID(),
      title: 'Growing Circle',
      description: 'Add 10 professional contacts',
      earned: false,
      icon: '🌟',
      category: 'milestone',
      requirement: 10,
      progress: 0,
      points: 50,
    },
    {
      id: crypto.randomUUID(),
      title: 'Network Master',
      description: 'Add 25 professional contacts',
      earned: false,
      icon: '👑',
      category: 'milestone',
      requirement: 25,
      progress: 0,
      points: 100,
    },
    {
      id: crypto.randomUUID(),
      title: 'Super Connector',
      description: 'Add 50 professional contacts',
      earned: false,
      icon: '💎',
      category: 'milestone',
      requirement: 50,
      progress: 0,
      points: 200,
    },
    {
      id: crypto.randomUUID(),
      title: 'Day One',
      description: 'Complete your first day of networking',
      earned: false,
      icon: '🔥',
      category: 'streak',
      requirement: 1,
      progress: 0,
      points: 5,
    },
    {
      id: crypto.randomUUID(),
      title: 'Week Warrior',
      description: 'Maintain a 7-day networking streak',
      earned: false,
      icon: '⚡',
      category: 'streak',
      requirement: 7,
      progress: 0,
      points: 50,
    },
    {
      id: crypto.randomUUID(),
      title: 'Consistency King',
      description: 'Maintain a 30-day networking streak',
      earned: false,
      icon: '🏆',
      category: 'streak',
      requirement: 30,
      progress: 0,
      points: 150,
    },
    {
      id: crypto.randomUUID(),
      title: 'Unstoppable',
      description: 'Maintain a 60-day networking streak',
      earned: false,
      icon: '💪',
      category: 'streak',
      requirement: 60,
      progress: 0,
      points: 300,
    },
    {
      id: crypto.randomUUID(),
      title: 'First Meeting',
      description: 'Schedule your first networking meeting',
      earned: false,
      icon: '📅',
      category: 'meetings',
      requirement: 1,
      progress: 0,
      points: 15,
    },
    {
      id: crypto.randomUUID(),
      title: 'Meeting Master',
      description: 'Schedule 5 networking meetings',
      earned: false,
      icon: '☕',
      category: 'meetings',
      requirement: 5,
      progress: 0,
      points: 40,
    },
    {
      id: crypto.randomUUID(),
      title: 'Coffee Champion',
      description: 'Schedule 10 networking meetings',
      earned: false,
      icon: '🎉',
      category: 'meetings',
      requirement: 10,
      progress: 0,
      points: 75,
    },
    {
      id: crypto.randomUUID(),
      title: 'Conversation Expert',
      description: 'Schedule 20 networking meetings',
      earned: false,
      icon: '🌟',
      category: 'meetings',
      requirement: 20,
      progress: 0,
      points: 150,
    },
    {
      id: crypto.randomUUID(),
      title: 'Early Bird',
      description: 'Log in before 9 AM',
      earned: false,
      icon: '🌅',
      category: 'engagement',
      requirement: 1,
      progress: 0,
      points: 10,
    },
    {
      id: crypto.randomUUID(),
      title: 'Goal Getter',
      description: 'Complete 10 daily goals',
      earned: false,
      icon: '✅',
      category: 'engagement',
      requirement: 10,
      progress: 0,
      points: 50,
    },
    {
      id: crypto.randomUUID(),
      title: 'Priority Pro',
      description: 'Set priority levels for 10 contacts',
      earned: false,
      icon: '⭐',
      category: 'engagement',
      requirement: 10,
      progress: 0,
      points: 30,
    },
    {
      id: crypto.randomUUID(),
      title: 'Note Taker',
      description: 'Add notes to 15 contacts',
      earned: false,
      icon: '📝',
      category: 'engagement',
      requirement: 15,
      progress: 0,
      points: 40,
    },
    {
      id: crypto.randomUUID(),
      title: 'Tag Master',
      description: 'Add tags to 20 contacts',
      earned: false,
      icon: '🏷️',
      category: 'engagement',
      requirement: 20,
      progress: 0,
      points: 35,
    },
    {
      id: crypto.randomUUID(),
      title: 'Quick Starter',
      description: 'Complete onboarding with sample data',
      earned: false,
      icon: '🚀',
      category: 'growth',
      requirement: 1,
      progress: 0,
      points: 15,
    },
    {
      id: crypto.randomUUID(),
      title: 'Profile Perfectionist',
      description: 'Complete your profile with all details',
      earned: false,
      icon: '👤',
      category: 'growth',
      requirement: 1,
      progress: 0,
      points: 20,
    },
    {
      id: crypto.randomUUID(),
      title: 'Resource Explorer',
      description: 'Visit the Resources section',
      earned: false,
      icon: '📚',
      category: 'growth',
      requirement: 1,
      progress: 0,
      points: 10,
    },
    {
      id: crypto.randomUUID(),
      title: 'Template User',
      description: 'Use 3 conversation templates',
      earned: false,
      icon: '💬',
      category: 'growth',
      requirement: 3,
      progress: 0,
      points: 25,
    },
    {
      id: crypto.randomUUID(),
      title: 'Diverse Network',
      description: 'Connect with professionals from 5 different industries',
      earned: false,
      icon: '🌐',
      category: 'connections',
      requirement: 5,
      progress: 0,
      points: 60,
    },
    {
      id: crypto.randomUUID(),
      title: 'LinkedIn Pro',
      description: 'Add LinkedIn URLs for 10 contacts',
      earned: false,
      icon: '💼',
      category: 'connections',
      requirement: 10,
      progress: 0,
      points: 30,
    },
    {
      id: crypto.randomUUID(),
      title: 'Contact Complete',
      description: 'Fill out all fields for 5 contacts',
      earned: false,
      icon: '✨',
      category: 'connections',
      requirement: 5,
      progress: 0,
      points: 45,
    },
    {
      id: crypto.randomUUID(),
      title: 'Follow-up Hero',
      description: 'Update last contact date for 10 contacts',
      earned: false,
      icon: '🔄',
      category: 'engagement',
      requirement: 10,
      progress: 0,
      points: 35,
    },
    {
      id: crypto.randomUUID(),
      title: 'Active Networker',
      description: 'Keep 15 contacts in active status',
      earned: false,
      icon: '💚',
      category: 'engagement',
      requirement: 15,
      progress: 0,
      points: 50,
    },
    {
      id: crypto.randomUUID(),
      title: 'Event Organizer',
      description: 'Complete 5 scheduled events',
      earned: false,
      icon: '🎯',
      category: 'meetings',
      requirement: 5,
      progress: 0,
      points: 60,
    },
    {
      id: crypto.randomUUID(),
      title: 'Weekly Planner',
      description: 'Schedule events for an entire week',
      earned: false,
      icon: '📆',
      category: 'meetings',
      requirement: 7,
      progress: 0,
      points: 45,
    },
    {
      id: crypto.randomUUID(),
      title: 'High Priority Focus',
      description: 'Have 5 high-priority contacts',
      earned: false,
      icon: '🔴',
      category: 'connections',
      requirement: 5,
      progress: 0,
      points: 30,
    },
    {
      id: crypto.randomUUID(),
      title: 'Points Collector',
      description: 'Earn 100 achievement points',
      earned: false,
      icon: '💯',
      category: 'milestone',
      requirement: 100,
      progress: 0,
      points: 25,
    },
    {
      id: crypto.randomUUID(),
      title: 'Points Master',
      description: 'Earn 500 achievement points',
      earned: false,
      icon: '🏅',
      category: 'milestone',
      requirement: 500,
      progress: 0,
      points: 100,
    },
    {
      id: crypto.randomUUID(),
      title: 'Elite Achiever',
      description: 'Earn 1000 achievement points',
      earned: false,
      icon: '👑',
      category: 'milestone',
      requirement: 1000,
      progress: 0,
      points: 200,
    },
    {
      id: crypto.randomUUID(),
      title: 'Weekend Worker',
      description: 'Network on a weekend',
      earned: false,
      icon: '🌴',
      category: 'streak',
      requirement: 1,
      progress: 0,
      points: 20,
    },
    {
      id: crypto.randomUUID(),
      title: 'Night Owl',
      description: 'Log in after 8 PM',
      earned: false,
      icon: '🦉',
      category: 'engagement',
      requirement: 1,
      progress: 0,
      points: 10,
    },
  ];
};
